name: CVRacing
main: org.cubeville.cvracing.CVRacing
authors: [Ptown16]
version: 1.20
api-version: 1.20
depend: [CVTools]
softdepend: [CVStats]
description: This is a plugin for racing on the server cubeville.org!

commands:
  race:
    description: CVRacing Base Command

permissions:

# Administration Commands
  cvracing.admin.scores:
    description: Allow a user to remove scores from a track
    default: op
  cvracing.admin.open:
    description: Allow a user to open a track
    default: op
  cvracing.admin.close:
    description: Allow a user to close a track
    default: op
  cvracing.admin.customization:
    description: Allow a user to set another person's customizations
    default: op
  cvracing.admin.commands:
    description: Allow the user to run various help commands
    default: op
  cvracing.admin.cpcommands.view:
    description: Allow a user to view a track's checkpoint commands
    default: op
  cvracing.admin.cpcommands.edit:
    description: Allow a user to edit a track's checkpoint commands
    default: op
  cvracing.admin.timing:
    description: Allow a user to edit a track's checkpoint commands
    default: op

# Track Setup Commands
  cvracing.setup.cps.view:
    description: Allow a user to view a track's checkpoints
    default: op
  cvracing.setup.cps.edit:
    description: Allow a user to edit a track's checkpoints
    default: op
  cvracing.setup.leaderboards.view:
    description: Allow a user to view a track's leaderboards
    default: op
  cvracing.setup.leaderboards.edit:
    description: Allow a user to edit a track's leaderboards
    default: op
  cvracing.setup.spawns.view:
    description: Allow a user to view a track's spawns
    default: op
  cvracing.setup.spawns.edit:
    description: Allow a user to edit a track's spawns
    default: op
  cvracing.setup.signs.view:
    description: Allow a user to view a track's signs
    default: op
  cvracing.setup.signs.edit:
    description: Allow a user to edit a track's signs
    default: op
  cvracing.setup.create:
    description: Allow a user to create a track
    default: op
  cvracing.setup.delete:
    description: Allow a user to delete a track
    default: op
  cvracing.setup.type:
    description: Allow a user to set the type of a track
    default: op
  cvracing.setup.tptocp:
    description: Allow a user to set the tptocp value of a track
    default: op
  cvracing.setup.spectate:
    description: Allow a user to set the spectate location of a track
    default: op
  cvracing.setup.exit:
    description: Allow a user to set the exit location of a track
    default: op
  cvracing.setup.rgreset:
    description: Allow a user to set the region reset location of a track (for tptocp)
    default: op
  cvracing.setup.center:
    description: Allow someone setting up a track to center their position in a block
    default: op

# Hosting Commands
  cvracing.host.players.edit:
    description: Allow a user to edit the players queued up for a hosted race
    default: op
  cvracing.host.players.view:
    description: Allow a user to view the players queued up for a hosted race
    default: op
  cvracing.host.countdown:
    description: Allow a user to start the countdown for a hosted race
    default: op
  cvracing.host.start:
    description: Allow a user to start a hosted race
    default: op
  cvracing.host.end:
    description: Allow a user to end a hosted race
    default: op
  cvracing.host.laps:
    description: Allow a user to set a specific number of laps for a race
    default: op
  cvracing.host.transfer:
    description: Allow a user to transfer hosting priveledges to another user
    default: op

# Customization Commands
  cvracing.customization.boat:
    description: Allow a user to set their boat color
    default: true
  cvracing.customization.horse.color:
    description: Allow a user to set their horse color
    default: true
  cvracing.customization.horse.style:
    description: Allow a user to set their horse style
    default: true
  cvracing.customization.horse.armor:
    description: Allow a user to set their horse armor
    default: true
  cvracing.customization.horse.armor.hex:
    description: Allow a user to set their horse armor to be a specific hex color
    default: true

# Citizen Commands
  cvracing.citizen.splits.use:
    description: Allow a user to use specific splits for their racing
    default: true
  cvracing.citizen.splits.compare:
    description: Allow a user to compare splits to another person, or between two people
    default: true
  cvracing.citizen.leaderboard:
    description: Allow a user to view the leaderboard for a track
    default: true
  cvracing.citizen.pb:
    description: Allow a user to view the personal best score for themselves or another user on a track
    default: true
  cvracing.citizen.rank:
    description: Allow a user to view the rank of themselves or another user on a track
    default: true
  cvracing.citizen.help:
    description: Allow a user to view boat racing commands
    default: true



